# Generated by Django 5.2.9 on 2026-02-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='categoria',
            field=models.CharField(blank=True, choices=[('set', 'Set'), ('pendiente', 'Pendiente'), ('accion', 'Acción')], default='set', max_length=50, null=True),
        ),
    ]
