# Generated by Django 6.0.2 on 2026-04-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0002_prompt_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='categoria',
            field=models.CharField(blank=True, choices=[('set', 'Set'), ('pendiente', 'Pendiente'), ('revision', 'Revision'), ('accion', 'Acción')], default='set', max_length=50, null=True),
        ),
    ]
