# Generated by Django 6.0.2 on 2026-04-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0004_set_prompt_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='prompts/'),
        ),
    ]
