# Generated by Django 6.0.2 on 2026-04-14 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0005_prompt_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='categoria',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('revision', 'Revision'), ('accion', 'Acción'), ('terminado', 'terminado')], default='revision', max_length=50),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='prompts.set'),
        ),
    ]
